//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.DLMS.AddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.DLMS.AddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports scope of access violated..
        /// </summary>
        internal static string AccessViolatedTxt {
            get {
                return ResourceManager.GetString("AccessViolatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a hardware fault..
        /// </summary>
        internal static string HardwareFaultTxt {
            get {
                return ResourceManager.GetString("HardwareFaultTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a inconsistent Class or Object..
        /// </summary>
        internal static string InconsistentClassTxt {
            get {
                return ResourceManager.GetString("InconsistentClassTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Name.
        /// </summary>
        internal static string LogicalNameTxt {
            get {
                return ResourceManager.GetString("LogicalNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Type.
        /// </summary>
        internal static string ManufacturerTypeTxt {
            get {
                return ResourceManager.GetString("ManufacturerTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordTxt {
            get {
                return ResourceManager.GetString("PasswordTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports Read-Write denied..
        /// </summary>
        internal static string ReadWriteDeniedTxt {
            get {
                return ResourceManager.GetString("ReadWriteDeniedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        internal static string ShortNameTxt {
            get {
                return ResourceManager.GetString("ShortNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a temporary failure..
        /// </summary>
        internal static string TemporaryFailureTxt {
            get {
                return ResourceManager.GetString("TemporaryFailureTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TypeWizardDescriptionTxt {
            get {
                return ResourceManager.GetString("TypeWizardDescriptionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TypeWizardHeaderTxt {
            get {
                return ResourceManager.GetString("TypeWizardHeaderTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unavailable object..
        /// </summary>
        internal static string UnavailableObjectTxt {
            get {
                return ResourceManager.GetString("UnavailableObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a undefined object..
        /// </summary>
        internal static string UndefinedObjectTxt {
            get {
                return ResourceManager.GetString("UndefinedObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error..
        /// </summary>
        internal static string UnknownErrorTxt {
            get {
                return ResourceManager.GetString("UnknownErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unmatched type..
        /// </summary>
        internal static string UnmatchedTypeTxt {
            get {
                return ResourceManager.GetString("UnmatchedTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select manufacturer and device type. Templates contain default settings for device types.
        /// </summary>
        internal static string WizardPage1DescriptionTxt {
            get {
                return ResourceManager.GetString("WizardPage1DescriptionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer and Device Type Selection.
        /// </summary>
        internal static string WizardPage1HeaderTxt {
            get {
                return ResourceManager.GetString("WizardPage1HeaderTxt", resourceCulture);
            }
        }
    }
}
